version: '3.3'

services:
  web:
    build: .
    ports:
      - "3040:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./js/frontend.js:/usr/share/nginx/html/js/frontend.js
      - ./nginx.conf:/etc/nginx/nginx.conf
